#!/usr/bin/env python
"""
This is a small script that does the equivalent of multicrab.
"""
import os
from optparse import OptionParser


from datetime import date


import CRABClient
from CRABAPI.RawCommand import crabCommand
from CRABClient.ClientExceptions import ClientException
from httplib import HTTPException


def getOptions():
    """
    Parse and return the arguments provided by the user.
    """
    usage = ("Usage: %prog --crabCmd CMD [--workArea WAD --crabCmdOpts OPTS]"
             "\nThe multicrab command executes 'crab CMD OPTS' for each project directory contained in WAD"
             "\nUse multicrab -h for help")

    parser = OptionParser(usage=usage)

    parser.add_option('-c', '--crabCmd',
                      dest = 'crabCmd',
                      default = '',
                      help = "crab command",
                      metavar = 'CMD')

    parser.add_option('-w', '--workArea',
                      dest = 'workArea',
                      default = '',
                      help = "work area directory (only if CMD != 'submit')",
                      metavar = 'WAD')

    parser.add_option('-o', '--crabCmdOpts',
                      dest = 'crabCmdOpts',
                      default = '',
                      help = "options for crab command CMD",
                      metavar = 'OPTS')

    (options, arguments) = parser.parse_args()

    if arguments:
        parser.error("Found positional argument(s): %s." % (arguments))
    if not options.crabCmd:
        parser.error("(-c CMD, --crabCmd=CMD) option not provided.")
    if options.crabCmd != 'submit':
        if not options.workArea:
            parser.error("(-w WAR, --workArea=WAR) option not provided.")
        if not os.path.isdir(options.workArea):
            parser.error("'%s' is not a valid directory." % (options.workArea))

    return options


def main():

    options = getOptions()

    # The submit command needs special treatment.
    if options.crabCmd == 'submit':
        today = date.today()
        d1 = today.strftime("%d_%m_%Y")
        #--------------------------------------------------------
        # This is the base config:
        #--------------------------------------------------------
        from CRABClient.UserUtilities import config
        config = config()

        config.General.requestName = None
        config.General.workArea = d1  #d1

        config.JobType.pluginName = 'Analysis'
        config.JobType.psetName = 'flyingtop_MC.py'
        config.JobType.inputFiles = ['TMVAClassification_BDTG_TRKSEL_.weights.xml','TMVAClassification_BDTG_EVTSEL_.weights.xml','TMVAClassification_BDTG_VTXSEL_.weights.xml','TMVAClassification_BDTG_VTXSel_TIGHTWP.weights.xml','Pileup_MC2018UL_bin100.root','MyDataPileupHistogram_bin100.root','RoccoR2018UL.txt']
        config.JobType.maxMemoryMB = 2500
        # config.JobType.numCores = 4

        config.Data.inputDataset = None
        config.Data.splitting = 'FileBased'
        config.Data.unitsPerJob = 20
        # config.Data.totalUnits = 20 # problem with data/ MC if we want tto quick check, we can uncomment this
        config.Data.outLFNDirBase = '/store/user/pvaucell/MC'
        config.Data.outputDatasetTag = 'MC'
        config.Data.inputDBS = 'global' #for signal : phys03 // for bkg :  global 
        config.Data.ignoreLocality = False
        config.Site.storageSite = 'T2_FR_IPHC' # Choose your site. 

        config.General.transferOutputs = True

        

        #--------------------------------------------------------

        # Will submit one task for each of these input datasets.
        inputDatasets = [
            
                        #  '/TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
                        #  '/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM',
                        #  '/ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM',
                        #  '/ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM',
                        #  '/DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM',
                        #  '/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
                        #  '/WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
                        #  '/WWTo2L2Nu_MLL_200To600_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM',
                        #  '/WWTo2L2Nu_MLL_600To1200_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM',
                        #  '/WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
                        #  '/ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
                        #  '/ttWJetsToLNu_5f_EWK_TuneCP5_13TeV_amcatnlo-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
			            #  '/TTZToLL_5f_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
			            #  '/TTToHadronic_TuneCP5CR1_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM',
			            #  '/TTWW_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
                        '/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'


                        #New Signal Samples at LO+1jet
                        # '/RPV_2018_smu200_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu230_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau001/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',

                        # '/RPV_smu200_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu230_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau003/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',

                        # '/RPV_smu200_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu230_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau010/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',

                        # '/RPV_smu200_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu230_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau030/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',

                        # '/RPV_2018_smu200_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu250_neu230_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER', 
                        # '/RPV_2018_smu300_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu300_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu300_neu250_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu300_neu250_ctau100_v3/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu300_neu250_ctau240_v2/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu300_neu280_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu350_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu350_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu350_neu250_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu350_neu300_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu350_neu330_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu250_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu300_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu350_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu400_neu380_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu250_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu300_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu350_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu400_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu450_neu430_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu180_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu200_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu250_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu300_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu350_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu400_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu450_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_2018_smu500_neu480_ctau100/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',


                        # '/RPV_smu200_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu230_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau300/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',

                        # '/RPV_smu200_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu250_neu230_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu250_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu300_neu280_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu250_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu300_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu350_neu330_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu250_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu300_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu350_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu400_neu380_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu250_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu300_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu350_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu400_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu450_neu430_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu180_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu200_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu550_neu250_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu300_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu350_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu400_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu450_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER',
                        # '/RPV_smu500_neu480_ctau1000/blochd-step4-9c0788701e974cfda4cc4ceabfa2b7bb/USER'
			                        ]

        for inDS in inputDatasets:
            # inDS is of the form /A/B/C. Since B is unique for each inDS, use this in the CRAB request name.
            config.Data.publication = False
            config.General.requestName = inDS.split('/')[1]
            config.Data.inputDataset = inDS
            config.Data.outputDatasetTag = '%s_%s' % (d1, config.General.requestName)
            # Submit.
            try:
                print "Submitting for input dataset %s" % (inDS)
                crabCommand(options.crabCmd, config = config, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Submission for input dataset %s failed: %s" % (inDS, hte.headers)
            except ClientException as cle:
                print "Submission for input dataset %s failed: %s" % (inDS, cle)

    # All other commands can be simply executed.
    elif options.workArea:

        for dir in os.listdir(options.workArea):
            projDir = os.path.join(options.workArea, dir)
            if not os.path.isdir(projDir):
                continue
            # Execute the crab command.
            msg = "Executing (the equivalent of): crab %s --dir %s %s" % (options.crabCmd, projDir, options.crabCmdOpts)
            print "-"*len(msg)
            print msg
            print "-"*len(msg)
            try:
                crabCommand(options.crabCmd, dir = projDir, *options.crabCmdOpts.split())
            except HTTPException as hte:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, hte.headers)
            except ClientException as cle:
                print "Failed executing command %s for task %s: %s" % (options.crabCmd, projDir, cle)


if __name__ == '__main__':
    main()
                                                                                                                      
                                                                                                                      # config.Data.inputDataset = '/TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYToMuMu_M-200To400_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM'
# config.Data.inputDataset = '/WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'


# config.Data.inputDataset = '/WJetsToQQ_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/WJetsToQQ_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/WJetsToQQ_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/QCD_Pt-50To80_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-80To120_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-170To300_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-300To470_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-470To600_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-600To800_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-800To1000_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_Pt-1000_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'

########
# config.Data.inputDataset = '/DYJetsToLL_M-4to50_HT-70to100_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-4to50_HT-100to200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-4to50_HT-200to400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v3/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-4to50_HT-400to600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-4to50_HT-600toInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/QCD_HT100to200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_HT200to300_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/QCD_HT300to500_TuneCP5_PSWeights_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/QCD_HT500to700_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/TTGamma_Dilept_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/TTGamma_SingleLept_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'

# config.Data.inputDataset = '/TTHH_TuneCP5_13TeV-madgraph-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/ttHTobb_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'
# config.Data.inputDataset = '/ttHToMuMu_M125_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM'

# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-70to100_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
# config.Data.inputDataset = '/DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM'
